### ISSUE TITLE
Falha em test_view_contract_detail e test_view_entry_detail

### ISSUE THREAD

**Issue by rg3915** [rg3915/orcamentos#26]
```
Creating test database for alias 'default'...
....................................................................FF.....FF.............
======================================================================
FAIL: test_get (orcamentos.proposal.tests.test_view_contract_detail.ContractDetailGet)
GET shuld return status 200
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rg3915/gh/my/orcamentos/orcamentos/proposal/tests/test_view_contract_detail.py", line 13, in test_get
    self.assertEqual(200, self.resp.status_code)
AssertionError: 200 != 404

======================================================================
FAIL: test_template (orcamentos.proposal.tests.test_view_contract_detail.ContractDetailGet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rg3915/gh/my/orcamentos/orcamentos/proposal/tests/test_view_contract_detail.py", line 16, in test_template
    self.assertTemplateUsed(self.resp, 'proposal/contract_detail.html')
  File "/home/rg3915/gh/my/orcamentos/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 579, in assertTemplateUsed
    self.fail(msg_prefix + "No templates used to render the response")
AssertionError: No templates used to render the response

======================================================================
FAIL: test_get (orcamentos.proposal.tests.test_view_entry_detail.EntryDetailGet)
GET shuld return status 200
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rg3915/gh/my/orcamentos/orcamentos/proposal/tests/test_view_entry_detail.py", line 13, in test_get
    self.assertEqual(200, self.resp.status_code)
AssertionError: 200 != 404

======================================================================
FAIL: test_template (orcamentos.proposal.tests.test_view_entry_detail.EntryDetailGet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rg3915/gh/my/orcamentos/orcamentos/proposal/tests/test_view_entry_detail.py", line 16, in test_template
    self.assertTemplateUsed(self.resp, 'proposal/entry_detail.html')
  File "/home/rg3915/gh/my/orcamentos/.venv/lib/python3.5/site-packages/django/test/testcases.py", line 579, in assertTemplateUsed
    self.fail(msg_prefix + "No templates used to render the response")
AssertionError: No templates used to render the response

----------------------------------------------------------------------
Ran 90 tests in 0.993s

FAILED (failures=4)
Destroying test database for alias 'default'...
```

**Comment by rg3915** [comment]
https://github.com/rg3915/orcamentos/commit/72597e8e4c21421ec6596b1c99fd8b7f282904f9

**Comment by paulo-romano** [comment]
Vou dar uma olhada.
